# Nombre y Puerto del microservicio
spring.application.name=mascotas-service
server.port=8083

# --- CONFIGURACIÓN BASE DE DATOS H2 ---
# generate-unique-name=false obliga a usar el nombre exacto 'mascotas_db'
spring.datasource.generate-unique-name=false
# DB_CLOSE_DELAY=-1 mantiene la base de datos viva mientras el microservicio corra
spring.datasource.url=jdbc:h2:mem:mascotas_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- CONSOLA H2 ---
# Permite entrar a la interfaz web que me mostraste
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# --- HIBERNATE / JPA ---
# Crea las tablas automáticamente al iniciar según tus archivos .java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Necesario para que reconozca el archivo import.sql si lo usas
spring.jpa.defer-datasource-initialization=true

# --- SEGURIDAD (JWT) ---
# Misma clave que los otros microservicios para consistencia
jwt.secret=patiperro-dev-secret-key-should-be-long-and-random-2026
jwt.expiration-ms=3600000

# --- CONFIGURACIÓN PARA FOTOS (HISTORIA DE USUARIO) ---
# Permite subir imágenes de hasta 3MB
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB

# Obliga a cargar los datos aunque la base de datos sea en memoria
spring.sql.init.mode=always


# Muestra en la terminal si hubo un error al insertar
spring.sql.init.continue-on-error=false
