spring.application.name=mascotas-service
server.port=8083

# --- CONFIGURACIÓN POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/mascotas_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto=update para que no borre tus datos de pgAdmin al reiniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- SEGURIDAD JWT ---
jwt.secret=patiperro-dev-secret-key-should-be-long-and-random-2026
jwt.expiration-ms=3600000
