spring.application.name=usuarios-service
server.port=8081

# Configuración de Base de Datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Habilita la consola para ver los datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console