spring.application.name=paseador-service
server.port=8082

# PostgreSQL (crear BD paseadores_db o ajustar URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/paseadores_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Misma clave y expiracion que tutores-service / api-gateway
jwt.secret=patiperro-dev-secret-key-should-be-long-and-random-2026
jwt.expiration-ms=3600000
